hellodjango/books/urls.py
from django.urls import path
from .views import books_list, book_details

app_name="books"

urlpatterns = [
    path("", books_list),
    path("<int:id>", book_details, name="details")
]

hellodjango/hellodjango/urls.py
from django.contrib import admin

from django.urls import path, include

from maths.views import hello_world, do_math

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", hello_world),
    path("hello/<name>", hello_world),
    path("maths/", include("maths.urls")),
    path("posty/", include("posts.urls")),
    path("books/", include("books.urls")),

    
    path('__debug__/', include('debug_toolbar.urls')),

]

hellodjango/maths/urls.py
from django.urls import path
from .views import do_math


urlpatterns = [
    path("<op>/<int:a>/<int:b>/", do_math),

]

hellodjango/posts/urls.py
from django.urls import path
from posts.views import posts_list, post_details


urlpatterns = [
    path("", posts_list),
    path("<int:id>", post_details, name="details")
]

hellodjango/authors/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=255)


    def __str__(self):
        return self.name

hellodjango/books/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey("authors.Author", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "ksiazka"
        verbose_name_plural = "ksiazki"

hellodjango/maths/models.py
from django.db import models

# Create your models here.



class Math(models.Model):

    OPERATION_CHOICES = (
        ("sum", "sum"),
        ("sub", "sub"),
        ("div", "div"),
        ("mul", "mul"),
    )

    op = models.CharField(verbose_name="Operation", max_length=3, choices=OPERATION_CHOICES)
    a = models.IntegerField()
    b = models.IntegerField()
    result = models.FloatField()
    comment = models.TextField(null=True, blank=True)


    def __str__(self):
        return f"op: {self.op} a: {self.a} b: {self.b}"


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    is_published = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"({self.id}) {self.title[:50]}"

hellodjango/posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    is_published = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"({self.id}) {self.title[:50]}"

hellodjango/authors/views.py
from django.shortcuts import render

# Create your views here.

hellodjango/books/views.py
from django.shortcuts import render
from .models import Book
from django.db import connection
# Create your views here.

def books_list(request):
    books = Book.objects.all()
    print(connection.queries)
    return render(
        request,
        "books/list.html",
        {"books": books}
    )

def book_details(request, id):
    book = Book.objects.get(id=id)
    return render(
        request,
        "books/details.html",
        {"book": book}
    )

hellodjango/maths/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Math

# Create your views here.

def hello_world(request, name="World"):
    return HttpResponse(f"Hello {name}")

def add(a: int, b: int) -> int:
    return a + b

def sub(a: int, b: int) -> int:
    return a - b


def mul(a: int, b: int) -> int:
    return a * b


def div(a: int, b: int) -> int | str:
    if b == 0:
        return "Dzielenie przez 0"
    return a / b


operations = {
    "add": add,
    "sub": sub,
    "div": div,
    "mul": mul
}


class Data:
    a = 10
    b = 20


def do_math(request, op, a, b):
    result = operations[op](a, b)
    maths = Math.objects.all()
    return render(
        request,
        "main.html",
        {
            "result": result,
            "lista": ["a", "b", "c"],
            "dictionary": {"Ala": "Kot"},
            "dane": Data(),
            "maths": maths,

        }
        )

    

hellodjango/posts/views.py
from django.shortcuts import render
from .models import Post
# Create your views here.

def posts_list(request):

    q = request.GET.get("title")
    before = request.GET.get("before")
    posts = Post.objects.all()
    if q:
        posts = posts.filter(title__icontains=q)
    
    if before:
        posts = posts.filter(created__lt=before)


# https://github.com/rkorzen/django3dcourse
        
    return render(
        request,
        "posts/main.html",
        {"posts": posts}
    )

def post_details(request, id):
    post = Post.objects.get(id=id)
    return render(
        request,
        "posts/details.html",
        {"post": post}
    )

hellodjango/books/templates/books/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    To jest main z books

    <ul>
    {% for book in books %}
        <li><a href="{% url 'books:details' book.id %}">{{ book.title }}</a></li>    
    {% endfor %}
    </ul>
</body>
</html>

hellodjango/maths/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    To jest main z maths
    {{result}}
    <br>
    {{lista.0}}
    {{dictionary.Ala}}
    {{dane.a}}

    {{ xxxx }}

    <table>
        {% for o in lista %}
        <tr class="{% cycle 'row1' 'row2' %}">
            <td>{{o|upper}}</td>
        </tr>

        {% endfor %}
    </table>

    <ul>
        {% for el in maths %}
            <li>{{ el }}</li>
        {% endfor %}
    </ul>

</body>
</html>

hellodjango/posts/templates/posts/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ post.title }}</h1>
    <p>{{ post.content }}</p>
</body>
</html>

hellodjango/posts/templates/posts/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    To jest main z posts

    <ul>
    {% for post in posts %}
        <li><a href="{% url 'details' post.id %}">{{ post.title }}</a></li>    
    {% endfor %}
    </ul>
</body>
</html>